services:
  app:
    build:
      context: .
      target: builder
    volumes:
      - uploads:/uploads
      - metadata:/metadata
    ports:
      - '8080:8080'
    env_file:
      - .env
    restart: unless-stopped

volumes:
  uploads:
  metadata:
