services:
  app:
    build:
      context: .
      target: builder
    environment:
      - LOG_LEVEL=debug
    volumes:
      - uploads:/uploads
    ports:
      - '8080:8080'
    env_file:
      - .env
    restart: unless-stopped

volumes:
  uploads:
  metadata:
