services:
  app:
    build: .
    volumes:
      - uploads:/uploads
    ports:
      - '8080:8080'
    env_file:
      - .env

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

volumes:
  uploads:

configs:
  qdrant_config:
    content: |
      log_level: INFO
