basePath: /api/v1/
info:
  contact:
    name: X7 team
  description: This is the API documentation for BucketX API.
  title: BucketX API
  version: "0.1"
paths:
  /:
    get:
      description: Welcome to bucketX API
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Welcome to bucketX API!"}'
          schema:
            additionalProperties: true
            type: object
      summary: Welcome to bucketX API
  /api/v1/file:
    post:
      consumes:
      - multipart/form-data
      description: Uploads a file to the server and returns the file's key and name.
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "File uploaded successfully", "filename": "example.txt",
            "file_key": "unique_file_key"}'
          schema:
            additionalProperties: true
            type: object
        "500":
          description: '{"error": "Detailed error message"}'
          schema:
            additionalProperties: true
            type: object
      summary: Upload a file
      tags:
      - files
  /api/v1/file/{file_key}:
    get:
      consumes:
      - application/json
      description: Fetch a file
      parameters:
      - description: File key
        in: path
        name: file_key
        required: true
        type: string
      - description: Transformation query
        in: query
        name: tr
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: file
        "404":
          description: '{"error": "Detailed error message"}'
          schema:
            additionalProperties: true
            type: object
      summary: Fetch a file
swagger: "2.0"
